---
- name: Add InfluxData GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Add InfluxData repository
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: Install Telegraf
  package:
    name: telegraf
    state: present

- name: Configure Telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    owner: root
    group: telegraf
    mode: "0640"
  notify: restart telegraf

- name: Start and enable Telegraf
  systemd:
    name: telegraf
    state: started
    enabled: true
    daemon_reload: true
